/* eslint-disable react-hooks/purity */
import { CalendarDays, ExternalLink, Video } from "lucide-react";
import { getMeetingPageData } from "@/lib/data/meeting.data";
import { MeetingFormDialog } from "./meeting-form-dialog";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default async function MeetingsPage() {
  const data = await getMeetingPageData();
  const isStaff = data.role === "institute-staff";
  const upcoming = data.meetings.filter((meeting) => new Date(meeting.scheduledAt) >= new Date() && meeting.status === "scheduled");
  return <div className="flex flex-col gap-6"><section className="flex flex-col justify-between gap-4 rounded-[28px] border border-primary/15 bg-card px-6 py-7 sm:flex-row sm:items-end"><div><p className="text-eyebrow text-primary">Live learning</p><h1 className="text-heading mt-2 text-3xl">{isStaff ? "Meet with your students." : "Your upcoming meetings."}</h1><p className="mt-2 text-sm text-muted-foreground">{isStaff ? "Schedule a class or course meeting and students will receive a notification with the join link." : "Join meetings scheduled for your class and enrolled courses."}</p></div>{isStaff ? <MeetingFormDialog classes={data.classes} courses={data.courses} /> : null}</section><div className="grid gap-4 sm:grid-cols-3"><Metric label="Upcoming" value={upcoming.length} /><Metric label={isStaff ? "Scheduled by you" : "All meetings"} value={data.meetings.length} /><Metric label="Next meeting" value={upcoming[0] ? new Date(upcoming[0].scheduledAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "—"} /></div><div className="grid gap-4 lg:grid-cols-2">{data.meetings.length === 0 ? <Card className="lg:col-span-2"><CardContent className="py-12 text-center text-muted-foreground"><Video className="mx-auto mb-3 size-8" />{isStaff ? "No meetings scheduled yet." : "No meetings have been scheduled for you yet."}</CardContent></Card> : data.meetings.map((meeting) => { const start = new Date(meeting.scheduledAt); const ended = start.getTime() + meeting.durationMinutes * 60000 < Date.now(); const canJoin = meeting.status === "scheduled" && !ended; return <Card key={meeting.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{meeting.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{meeting.audienceLabel}{meeting.hostName ? ` · Hosted by ${meeting.hostName}` : ""}</p></div><Badge variant={meeting.status === "cancelled" ? "destructive" : ended ? "secondary" : "success"}>{meeting.status === "cancelled" ? "Cancelled" : ended ? "Ended" : "Scheduled"}</Badge></div></CardHeader><CardContent><div className="flex items-center gap-2 text-sm"><CalendarDays className="size-4 text-primary" />{start.toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })} · {meeting.durationMinutes} min</div>{meeting.description ? <p className="mt-3 text-sm text-muted-foreground">{meeting.description}</p> : null}{canJoin ? <a className={`${buttonVariants({ variant: "default" })} mt-4 w-full`} href={meeting.meetingUrl} target="_blank" rel="noopener noreferrer">Join meeting <ExternalLink /></a> : <span className={`${buttonVariants({ variant: "secondary" })} mt-4 w-full cursor-not-allowed opacity-60`}>Meeting unavailable</span>}</CardContent></Card>; })}</div></div>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>; }
