import { listPayherePayments } from "@/lib/data/subscription.data";
import { Badge } from "@/components/ui/badge";
import { DataTableCard, type DataTableRow } from "@/components/data-table/data-table-card";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const columns = [{ key: "institute", header: "Institute", sortable: true }, { key: "plan", header: "Plan", sortable: true }, { key: "reference", header: "References", sortable: true }, { key: "amount", header: "Amount", sortable: true }, { key: "status", header: "Status", sortable: true }, { key: "processing", header: "Webhook processing" }];
function statusVariant(status: string) { if (status === "success") return "success" as const; if (status === "pending" || status === "processing") return "warning" as const; if (status === "failed" || status === "chargeback") return "destructive" as const; return "secondary" as const; }

export default async function PayherePaymentsPage() {
  const payments = await listPayherePayments();
  const rows: DataTableRow[] = payments.map((payment) => {
    const institute = payment.instituteId as unknown as { name?: string; code?: string } | null;
    const plan = payment.planId as unknown as { name?: string } | null;
    return { key: String(payment._id), searchValue: `${institute?.name ?? ""} ${institute?.code ?? ""} ${plan?.name ?? ""} ${payment.checkoutSnapshot.planName} ${payment.orderId} ${payment.payherePaymentId ?? ""} ${payment.status}`, sortValues: [institute?.name ?? "", payment.checkoutSnapshot.planName, payment.orderId, payment.amount, payment.status, null], filterValues: { status: payment.status }, cells: [<div key="institute"><p className="font-medium">{institute?.name ?? "Unknown institute"}</p><p className="text-xs text-muted-foreground">{institute?.code ?? "No code"}</p></div>, <div key="plan"><p className="font-medium">{payment.checkoutSnapshot.planName}</p><p className="text-xs text-muted-foreground capitalize">{payment.checkoutSnapshot.billingInterval} · {plan?.name ?? "Deleted plan"}</p></div>, <div key="reference" className="font-mono text-xs"><p>{payment.orderId}</p><p className="mt-1 text-muted-foreground">{payment.payherePaymentId ? `PayHere: ${payment.payherePaymentId}` : "PayHere ID pending"}</p></div>, `${payment.currency} ${payment.amount.toFixed(2)}`, <Badge key="status" variant={statusVariant(payment.status)} className="capitalize">{payment.status}</Badge>, <div key="processing" className="max-w-64 text-xs text-muted-foreground"><p>{payment.processedAt ? `Processed ${new Date(payment.processedAt).toLocaleString()}` : payment.processingAt ? `Claimed ${new Date(payment.processingAt).toLocaleString()}` : "Not processed"}</p>{payment.providerStatusCode ? <p className="mt-1">Provider code: {payment.providerStatusCode}</p> : null}{payment.failureReason ? <p className="mt-1 text-destructive">{payment.failureReason}</p> : null}</div>] };
  });
  return <div className="flex flex-col gap-6"><div><p className="text-eyebrow text-primary">Payment provider</p><h1 className="text-heading mt-2 text-3xl">PayHere payments</h1><p className="mt-2 text-sm text-muted-foreground">Provider transactions and verified webhook processing. Manual bank, cash, cheque, and card-manual records remain in the invoice and reconciliation workflows.</p></div><Card><CardHeader><CardTitle>PayHere record handling</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-muted-foreground">A successful PayHere record is confirmed through the server webhook and automatically reconciled. Provider payloads are intentionally not shown here; use the references and processing state for support and reconciliation.</CardContent></Card><DataTableCard title="Transactions" sub="Search by institute, plan, order ID, PayHere payment ID, or status." columns={columns} rows={rows} searchPlaceholder="Search PayHere transactions..." emptyTitle="No PayHere payment records yet." filters={[{ key: "status", label: "Status", options: ["pending", "processing", "success", "failed", "cancelled", "chargeback"].map((value) => ({ value, label: value.charAt(0).toUpperCase() + value.slice(1) })) }]} /></div>;
}
