import Link from "next/link";
import { Building2, Landmark, WalletCards } from "lucide-react";
import { createPlatformBankAccount } from "@/lib/actions/platform-bank-account.actions";
import { getPlatformBankAccounts } from "@/lib/data/platform-bank-account.data";
import { formatLkr } from "@/lib/currency";
import { StatCard } from "@/components/dashboard-shell/stat-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

export default async function PlatformBanksPage() {
  const accounts = await getPlatformBankAccounts();
  const pending = accounts.reduce((sum, account) => sum + account.awaitingCount, 0);
  return <div className="flex flex-col gap-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-eyebrow text-primary">Platform banking</p><h1 className="text-heading mt-2 text-3xl">Bank accounts, clearly managed.</h1><p className="mt-2 text-sm text-muted-foreground">Keep the accounts used for subscription collections and manual payment reconciliation in one controlled place.</p></div><Link href="/billing/reconciliation" className="text-sm font-semibold text-primary hover:underline">Open reconciliation queue →</Link></div><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Active bank accounts" icon={Landmark} value={accounts.filter((account) => account.isActive).length} tone="primary" /><StatCard label="Default collection account" icon={WalletCards} value={accounts.find((account) => account.isDefault)?.bankName ?? "Not set"} tone="info" /><StatCard label="Unmatched payments" icon={Building2} value={pending} sub="Across registered accounts" tone="warning" /></div><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><Card><CardHeader><CardTitle>Platform bank accounts</CardTitle></CardHeader><CardContent>{accounts.length ? <div className="grid gap-3 sm:grid-cols-2">{accounts.map((account) => <div key={String(account._id)} className="rounded-2xl border border-border/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{account.bankName}</p><p className="mt-1 text-sm text-muted-foreground">{account.accountName}</p></div>{account.isDefault ? <Badge variant="success">Default</Badge> : null}</div><p className="mt-4 font-mono text-sm">•••• {account.accountNumber.slice(-4)}</p><p className="mt-1 text-xs text-muted-foreground">{account.branch || "Branch not specified"}</p><div className="mt-4 border-t pt-3 text-sm"><p className="font-medium">{account.awaitingCount} unmatched payment{account.awaitingCount === 1 ? "" : "s"}</p><p className="text-xs text-muted-foreground">{formatLkr(account.awaitingAmount)} awaiting reconciliation</p></div></div>)}</div> : <p className="text-sm text-muted-foreground">Add the first platform collection account.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Add bank account</CardTitle></CardHeader><CardContent><form action={createPlatformBankAccount} className="space-y-3"><Input name="bankName" placeholder="Bank name" required /><Input name="accountName" placeholder="Account name" required /><Input name="accountNumber" placeholder="Account number" required /><Input name="branch" placeholder="Branch (optional)" /><label className="flex items-center gap-2 text-sm"><input name="isDefault" type="checkbox" /> Set as default collection account</label><Button className="w-full">Add bank account</Button></form></CardContent></Card></div></div>;
}
