import { StyleSheet, Document, Page, Text, View } from "@react-pdf/renderer";
import type { ReactNode } from "react";

export const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#172033",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingBottom: 12,
    borderBottom: "2 solid #2563eb",
  },
  instituteName: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: "#0f172a",
  },
  docTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
    color: "#1d4ed8",
  },
  docMeta: {
    fontSize: 9,
    color: "#64748b",
    textAlign: "right",
    marginTop: 2,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    textTransform: "uppercase",
    color: "#2563eb",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  label: {
    color: "#64748b",
  },
  value: {
    fontFamily: "Helvetica-Bold",
  },
  table: {
    marginTop: 8,
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1 solid #e2e8f0",
    paddingVertical: 6,
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#0f172a",
    color: "#ffffff",
    paddingHorizontal: 6,
    paddingVertical: 7,
    marginBottom: 2,
    fontFamily: "Helvetica-Bold",
  },
  tableCell: {
    flex: 1,
  },
  tableCellRight: {
    flex: 1,
    textAlign: "right",
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 32,
    right: 32,
    fontSize: 8,
    color: "#64748b",
    textAlign: "center",
    borderTop: "1 solid #e2e8f0",
    paddingTop: 8,
  },
});

export function PdfPage({
  instituteName,
  docTitle,
  docMeta,
  children,
}: {
  instituteName: string;
  docTitle: string;
  docMeta?: string;
  children: ReactNode;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.instituteName}>{instituteName}</Text>
          <View>
            <Text style={styles.docTitle}>{docTitle}</Text>
            {docMeta ? <Text style={styles.docMeta}>{docMeta}</Text> : null}
          </View>
        </View>
        {children}
        <Text style={styles.footer}>Generated by LearningMS</Text>
      </Page>
    </Document>
  );
}

export function PdfRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}
