import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 28, fontFamily: "Helvetica", fontSize: 7, color: "#1a1a1a" },
  header: { marginBottom: 16, paddingBottom: 10, borderBottom: "2 solid #1a1a1a" },
  title: { fontFamily: "Helvetica-Bold", fontSize: 16 },
  meta: { marginTop: 3, color: "#555555", fontSize: 9 },
  headerRow: { flexDirection: "row", borderBottom: "1 solid #1a1a1a", paddingBottom: 5, marginBottom: 2 },
  row: { flexDirection: "row", borderBottom: "1 solid #e5e5e5", paddingVertical: 4 },
  cell: { flex: 1, paddingRight: 4 },
  headerCell: { fontFamily: "Helvetica-Bold" },
  footer: { position: "absolute", bottom: 16, left: 28, right: 28, textAlign: "center", color: "#777777" },
});

export function TabularReportPdf({
  title,
  columns,
  rows,
}: {
  title: string;
  columns: { key: string; header: string }[];
  rows: Record<string, unknown>[];
}) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.meta}>Generated {new Date().toLocaleString()}</Text>
        </View>

        <View style={styles.headerRow} fixed>
          {columns.map((column) => (
            <Text key={column.key} style={[styles.cell, styles.headerCell]}>{column.header}</Text>
          ))}
        </View>
        {rows.map((row, index) => (
          <View key={index} style={styles.row} wrap={false}>
            {columns.map((column) => (
              <Text key={column.key} style={styles.cell}>{String(row[column.key] ?? "")}</Text>
            ))}
          </View>
        ))}
        <Text style={styles.footer} fixed>Generated by LearningMS</Text>
      </Page>
    </Document>
  );
}
