import ExcelJS from "exceljs";
import type { CsvColumn } from "./csv";

export async function toXlsxBuffer<T extends Record<string, unknown>>(
  rows: T[],
  columns: CsvColumn<T>[],
  sheetName = "Sheet1"
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "LearningMS";
  workbook.created = new Date();
  const sheet = workbook.addWorksheet(sheetName);

  const reportTitle = sheetName.replace(/[-_]/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
  sheet.mergeCells(1, 1, 1, Math.max(columns.length, 1));
  const titleCell = sheet.getCell("A1");
  titleCell.value = `${reportTitle} Report`;
  titleCell.font = { name: "Aptos Display", size: 16, bold: true, color: { argb: "FFFFFFFF" } };
  titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1D4ED8" } };
  titleCell.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 30;
  sheet.mergeCells(2, 1, 2, Math.max(columns.length, 1));
  sheet.getCell("A2").value = `Generated by LearningMS · ${new Date().toLocaleString("en-LK")}`;
  sheet.getCell("A2").font = { size: 10, color: { argb: "FF64748B" } };

  const summaryItems = [
    ["TOTAL RECORDS", String(rows.length)],
    ["INCLUDED FIELDS", String(columns.length)],
    ["FORMAT", "XLSX"],
  ] as const;
  for (const [index, [label, value]] of summaryItems.entries()) {
    if (index >= columns.length) break;
    const cell = sheet.getCell(4, index + 1);
    cell.value = `${label}\n${value}`;
    cell.font = { name: "Aptos", size: 10, bold: true, color: { argb: "FF0F172A" } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F5F9" } };
    cell.alignment = { vertical: "middle", wrapText: true };
    cell.border = { top: { style: "thin", color: { argb: "FFCBD5E1" } }, bottom: { style: "thin", color: { argb: "FFCBD5E1" } } };
  }
  sheet.getRow(4).height = 32;

  sheet.columns = columns.map((column) => ({
    key: String(column.key),
    width: Math.min(Math.max(column.header.length + 5, 15), 34),
  }));
  const headerRowNumber = 6;
  const headerRow = sheet.getRow(headerRowNumber);
  headerRow.values = columns.map((column) => column.header);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0F172A" } };
  headerRow.alignment = { vertical: "middle", wrapText: true };
  headerRow.height = 22;

  for (const row of rows) {
    const added = sheet.addRow(Object.fromEntries(columns.map((column) => [column.key, row[column.key] ?? ""])));
    added.alignment = { vertical: "top", wrapText: true };
    if (added.number % 2 === 1) added.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF8FAFC" } };
  }
  sheet.autoFilter = { from: { row: headerRowNumber, column: 1 }, to: { row: Math.max(headerRowNumber, rows.length + headerRowNumber), column: columns.length } };
  sheet.views = [{ state: "frozen", ySplit: headerRowNumber }];
  sheet.eachRow((row) => row.eachCell((cell) => { cell.border = { bottom: { style: "hair", color: { argb: "FFE2E8F0" } } }; }));

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
