import {
  BarChart3,
  CircleDollarSign,
  ReceiptText,
  TrendingDown,
  TrendingUp,
} from "lucide-react";
import { getRevenueAnalytics } from "@/lib/data/subscription.data";
import { StatCard } from "@/components/dashboard-shell/stat-card";
import { TrendChart } from "@/components/dashboard-shell/trend-chart";
import { DonutChart } from "@/components/dashboard-shell/donut-chart";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatLkr } from "@/lib/currency";

const money = (value: number) => formatLkr(value);

export default async function RevenueAnalyticsPage() {
  const analytics = await getRevenueAnalytics();
  const change = analytics.previousCollected
    ? ((analytics.collected - analytics.previousCollected) /
        analytics.previousCollected) *
      100
    : 0;
  const planRevenue = analytics.plans.map((plan) => ({
    key: plan.name,
    label: plan.name,
    value: plan.revenue,
  }));
  return (
    <div className="flex flex-col gap-6">
      <div>
        <p className="text-eyebrow text-primary">Commercial intelligence</p>
        <h1 className="text-heading mt-2 text-3xl">Revenue analytics</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Recurring revenue, collection performance, and the subscriptions
          shaping the next quarter.
        </p>
      </div>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          label="MRR"
          icon={CircleDollarSign}
          value={money(analytics.mrr)}
          sub={`${analytics.activeSubscriptions} active subscriptions`}
          tone="primary"
        />
        <StatCard
          label="ARR"
          icon={TrendingUp}
          value={money(analytics.arr)}
          sub="Current annual run rate"
          tone="info"
        />
        <StatCard
          label="Collected this month"
          icon={ReceiptText}
          value={money(analytics.collected)}
          sub={`${change >= 0 ? "+" : ""}${change.toFixed(1)}% from last month`}
          tone="success"
        />
        <StatCard
          label="Collection rate"
          icon={BarChart3}
          value={`${analytics.collection.toFixed(0)}%`}
          sub="Paid invoices issued this month"
          tone="warning"
        />
      </div>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(22rem,1fr)]">
        <TrendChart
          title="Six-month collections"
          sub="Paid platform invoices by month."
          data={analytics.trend.map((point) => ({
            label: point.month,
            value: point.totalPaid,
          }))}
          format="currency"
          emptyLabel="No paid invoices in this period."
        />
        <DonutChart
          title="MRR by plan"
          sub="How active recurring revenue is distributed."
          data={planRevenue}
          emptyLabel="No active subscriptions yet."
        />
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>90-day forecast</CardTitle>
            <p className="text-sm text-muted-foreground">
              A run-rate forecast based on current active subscriptions.
            </p>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold">
              {money(analytics.forecast)}
            </p>
            <p className="mt-2 text-sm text-muted-foreground">
              Expected recurring revenue over the next three months, before
              churn, discounts, or plan changes.
            </p>
            <div className="mt-6 grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-muted-foreground">New subscriptions</p>
                <p className="mt-1 text-xl font-semibold">
                  {analytics.newSubscriptions}
                </p>
              </div>
              <div>
                <p className="text-muted-foreground">Cancelled this month</p>
                <p className="mt-1 flex items-center gap-1 text-xl font-semibold">
                  <TrendingDown className="size-4" />
                  {analytics.cancelledSubscriptions}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Revenue by plan</CardTitle>
            <p className="text-sm text-muted-foreground">
              Monthly recurring value generated by active plan assignments.
            </p>
          </CardHeader>
          <CardContent>
            <div className="divide-y">
              {analytics.plans.length ? (
                analytics.plans.map((plan) => (
                  <div
                    key={plan.name}
                    className="flex items-center justify-between py-3 text-sm"
                  >
                    <div>
                      <p className="font-medium">{plan.name}</p>
                      <p className="text-muted-foreground">
                        {plan.subscribers} active institutes
                      </p>
                    </div>
                    <p className="font-semibold">{money(plan.revenue)}/mo</p>
                  </div>
                ))
              ) : (
                <p className="text-sm text-muted-foreground">
                  No active subscriptions yet.
                </p>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
